sudo: required
services:
  - docker

before_install:
  - docker build -t test -f Dockerfile.dev .

script:
  - docker run -e CI=true test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env : "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-851858764444"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws secret"
